# Generated by Django 3.2 on 2021-05-28 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='Compelete',
            new_name='compelete',
        ),
    ]
