# Generated by Django 3.2 on 2021-05-28 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_compelete_task_compelete'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='compelete',
            new_name='compeleted',
        ),
    ]
