# Generated by Django 3.2 on 2021-05-28 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_compelete_task_compeleted'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='compeleted',
            new_name='completed',
        ),
    ]
